### ISSUE TITLE
Approvers: permission level vs CODEOWNERS

### ISSUE THREAD

**Issue by pellared** [signalfx/gdi-specification#58]
Currently, the spec says
```
MUST grant Triage permission level to approvers
...
MUST have a .github/CODEOWNERS file with approvers
```

The problem is that at least `Write` permission is required to act as a code owner. I would not advise giving approvers `Write` permission as it would allow them (at least) to create tags and add/delete/edit GH releases.

I think that what we can do is to change the CODEOWNER description to:

```
MUST have a .github/CODEOWNERS file with maintainers
```

And additionally, create a GH workflow like this (we can put this and CODOEWNER template into [docs/templates](https://github.com/signalfx/gdi-specification/tree/main/docs/templates) directory):

```yaml
name: Request review on PRs

on:
  pull_request:
    types:
      - opened

jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: ubuntu-20.04

    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer signalfx/REPO-approvers
```

It should be also in line with @iNikem proposal to use teams. See: https://github.com/signalfx/gdi-specification/issues/53

References:
- https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level
- https://stackoverflow.com/questions/66557514/how-to-automatically-request-a-review-from-someone-using-github-actions
